version: "3"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - monitoring
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
  k6:
    image: grafana/k6:latest
    container_name: k6
    depends_on:
      - influxdb
    ports:
      - "6565:6565"
    networks:
      - monitoring
    volumes:
      - ./scripts:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
networks:
  monitoring:
